### ISSUE TITLE
mkvalidator should print out the filename or other identifier

### ISSUE THREAD

**Issue by bastik-tor** [Matroska-Org/foundation-source#10]
I'm on Windows and when I do

`CMD /k C:\mkvalidator\mkvalidator.exe $path\$filename.ext`

with mkvalidator 0.5.0

I get:
`mkvalidator 0.5.0: the file appears to be valid`
`file created with [...]`

It does not tell me the filename of the file it has processed. If I want to feed mkvalidator files automatically I wont have an overview which of the files output an error or warning.

**Comment by robUx4** [comment]
Added in the next release with dd767f497b5e13c7d056deb0be16eac8bf984579
