### ISSUE TITLE
After compiling and build -> -bash: mkvalidator: command not found

### ISSUE THREAD

**Issue by Speedmod88** [Matroska-Org/foundation-source#113]
Hello

Need some help... My debian don't find mkvalidator 

I installed using

git clone **
cd foundation-source
cmake .
make
100% build without error

and it don't find mkvalidator cmd line

-------------------------------------------------
mkvalidator --version
-bash: mkvalidator: command not found

using: Debian

thanks

**Comment by robUx4** [comment]
If it built successfully, the binary should be somewhere before proper installation (`cmake --install`).

You can find it with:
> find . -type f -name mkvalidator

**Comment by robUx4** [comment]
I did the same command in my Ubuntu and I got this
```sh
$ find . -type f -name mkvalidator
./mkvalidator/mkvalidator
```
