### ISSUE TITLE
Assertion failure in mkclean

### ISSUE THREAD

**Issue by gmbuell** [Matroska-Org/foundation-source#125]
I've got an mkv that passes mkvalidator (i.e. "the file appears to be valid") but running mkclean --remux --optimize on the file results in:
```
Progress 1/3: 100%
Optimizing...
Remuxing...
mkclean: /home/gmbuell/github/foundation-source/mkclean/mkclean.c:2308: main: Assertion `pBlockInfo->DecodeTime == MATROSKA_BlockTimestamp(pBlockInfo->Block)' failed.
Aborted (core dumped)
```

This is with a new build of mkclean from pulled today. mkclean works on other mkvs. Just not this one. What other information can I provide to help diagnose?

**Comment by robUx4** [comment]
Can you provide the file ? Or alternatively test with the latest master ?

**Comment by gmbuell** [comment]
Unfortunately at this point I have no idea what the source file was anymore so I'll close this issue.
