### ISSUE TITLE
all tools compilation error with msvc on windows X64: z.lib (instead of zlib.lib) inside vcproj file  

### ISSUE THREAD

**Issue by NSP-0123456** [Matroska-Org/foundation-source#156]
I use cmake -S . -B build
and then in build folder i use 
msbuild -p:configuration=release -p:Platform=x64 /t:Clean,Build ALL_BUILD.vcxproj 

I have compilation error asking for z.lib to be linked in windows zlib static lib name is zlib.lib unless compiled from source wih different name.

In folder libmatroska2, file CMakeLists.txt you have the current expression:
if (CONFIG_ZLIB)
  if(ZLIB_FOUND)
    target_link_libraries("matroska2" PRIVATE $<BUILD_INTERFACE:z>) 

if zib is already installed it asks for a z.lib which is not the name of zlib library.

**Comment by robUx4** [comment]
Thanks for the prompt report. Let me know if the fix from #167 doesn't work.
