### ISSUE TITLE
mkclean doesn't support the A_OPUS codec ID for the WebM profile

### ISSUE THREAD

**Issue by vhmth** [Matroska-Org/foundation-source#18]
Chrome's [MediaRecorder](https://developers.google.com/web/updates/2016/01/mediarecorder) API records audio in Opus format. Would be awesome to have support for this in `mkclean` and `mkvalidator`. Not sure how much work this would be, but I'm down to contribute if you guys could point me to a general area of the codebase.

**Comment by vhmth** [comment]
Here is a complete list of codecs that the Chrome MediaRecorder supports. Audio seems to be opus-only for video recordings:

https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/mediarecorder/MediaRecorder-isTypeSupported.html

**Comment by robUx4** [comment]
Fixed by https://github.com/Matroska-Org/foundation-source/commit/6b53c221f159b362a3dd7f8809cc8f5791c2f169
