### ISSUE TITLE
mkvalidator 0.5.0 and non-ASCII characters

### ISSUE THREAD

**Issue by mkver** [Matroska-Org/foundation-source#21]
Hello,

although mkvalidator can handle non-latin command-line characters on windows since version 0.4.1 (according to the changelog), it can't even handle simple German umlauts for me.
I also tested version 4.0 (after all, Latin-1 and CP 1252 contains umlauts, so maybe it worked in version 0.4.0 and maybe [the commit](https://github.com/Matroska-Org/foundation-source/commit/6af0312caadc4c1f598441415ad67500546f4c77) broke it), but this didn't work, either.

Thanks in advance
Andi

**Comment by mkver** [comment]
Sorry, I seem to have messed things a bit up: I have mkvalidator 0.5.0 in my path variable and in reality I have not tested version 0.4.0. Now I have and it turns out that this commit indeed changed the situation regarding umlauts: Version 0.4.0 has no problems with them.

**Comment by robUx4** [comment]
Are you using a custom build or the official build ? There might have been an issue in the last build as UNICODE was not always set in VisualStudio builds. That should work in the next release.

**Comment by mkver** [comment]
I was using the official 0.50 build from [sourceforge](https://sourceforge.net/projects/matroska/files/mkvalidator/mkvalidator-win32.v0.5.0.zip/download) which didn't like Umlauts. After you released version 0.51 I checked and saw no Windows builds in [the release page](https://github.com/Matroska-Org/foundation-source/releases) and the version on [matroska.org](https://matroska.org/downloads/windows.html) was still 0.50, so I thought that you might have stopped creating Windows builds. But I should have looked at sourceforge. Anyway, umlauts and even kyrillic names work fine in releases 0.5.1 and 0.5.2. So this issue could have been closed a long time ago. Sorry for that.

**Comment by mkver** [comment]
Addendum: With "work fine" I mean that mkvalidator can find these files and checks them; but it appears to me that the standard error stream is in CP-1252, whereas the default codepage for cmd.exe is OEM 850 (at least in my localization). Therefore the file name that mkvalidator emits is displayed incorrectly by default. E.g. ü becomes ³.
But as I said: I'm fine with this.
