### ISSUE TITLE
[wish] release mkvalidator 0.5.2 on Brew

### ISSUE THREAD

**Issue by retokromer** [Matroska-Org/foundation-source#30]
[There](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mkvalidator.rb) is still 0.5.0.

**Comment by retokromer** [comment]
ping

**Comment by retokromer** [comment]
Closing. I personally don’t need it anymore, because my workshop is now over.

**Comment by robUx4** [comment]
Someone with a mac would have to do this.

**Comment by retokromer** [comment]
Thank you! The Brew [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mkvalidator.rb) has just been updated.
