### ISSUE TITLE
Non-UNIX line endings in configure cause build failure on macOS

### ISSUE THREAD

**Issue by ilovezfs** [Matroska-Org/foundation-source#31]
Using the 0.5.2 release tarball from https://sourceforge.net/projects/matroska/files/mkvalidator/mkvalidator-0.5.2.tar.bz2/download the build fails on macOS:
```
bash-3.2$ ./configure
bash: ./configure: /bin/sh^M: bad interpreter: No such file or directory
bash-3.2$ 
```
Running dos2unix on `configure` fixes it.

**Comment by robUx4** [comment]
Since we're using CMake it's fixed.
