### ISSUE TITLE
Is mkclean safe to use on newer audio formats?

### ISSUE THREAD

**Issue by Nottt** [Matroska-Org/foundation-source#32]
I've heard it might not be "safe", can we get a official answer on this issue?

Is there any issue using mkclean with mkv with newer audio formats such as TrueHD, DTS? 

Also why it seems that mediainfo information is lost?

![mkclean](https://user-images.githubusercontent.com/13532436/32752162-4d2c40f8-c8af-11e7-8b8b-d52fd2b21ea9.png)

Left is file after mkclean and right before.

**Comment by robUx4** [comment]
It should be safe, yes. Not sure what MediaInfo does to compute the bitrate, but the rest of the information is the same.
`mkclean` doesn't know about codec data (apart from Vorbis which needs to be parsed) so whatever new codec there is, it makes no difference for the handling. One possible issue was when Opus was introduced and needed some extra elements. Once these elements are supported it makes no difference.

**Comment by Nottt** [comment]
I love mkclean, but this bit rate stuff is holding me off. I use a lot of
software that uses mediainfo to parse information about files. If the bit
rate doesn't show up anymore it will confuse them.

I noticed this doesn't seem to always happen, but still happens like 90% of
the time.

All my files are produced with makemkv with I assume is a "good"
application that should write good mkv. And they can include the bitrate in
the output.

Could this be a bug?

**Comment by mbunkus** [comment]
You should really ask the MediaInfo developers why MediaInfo doesn't show certain information for those files.
