### ISSUE TITLE
mkclean drops new elements

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/foundation-source#33]
I'd like to clean a Matroska file but it seems to drop many elements in the process. For instance:

Create sample:
`ffmpeg -f lavfi -i testsrc=d=1 -color_primaries smpte170m -color_trc bt709 -colorspace smpte170m -color_range mpeg -vf setfield=bff,setsar=40/27,setdar=4/3 ffmpeg.mkv`

Then clean:
```
mkclean ffmpeg.mkv 
Progress 1/3: 100%
The TransferCharacteristics element at 464 is not part of profile 'matroska v2', skipping
The Primaries element at 472 is not part of profile 'matroska v2', skipping
The Range element at 476 is not part of profile 'matroska v2', skipping
The Colour element at 461 is not part of profile 'matroska v2', skipping
The FieldOrder element at -1 is not part of profile 'matroska v2', skipping
The SeekPreRoll element at -1 is not part of profile 'matroska v2', skipping
Progress 3/3: 100%
Finished cleaning & optimizing "clean.ffmpeg.mkv"
```

In the help doc, there is no option to use a `matroska v4` profile:
```
mkclean
mkclean v0.8.10, Copyright (c) 2010-2011 Matroska Foundation
Usage: mkclean [options] <matroska_src> [matroska_dst]
Options:
  --keep-cues   keep the original Cues content and move it to the front
  --remux       redo the Clusters layout
  --doctype <v> force the doctype version
    1: 'matroska' v1
    2: 'matroska' v2
    3: 'matroska' v3
    4: 'webm'
    5: 'matroska' v1 with DivX extensions
```

Is it possible to clean without dropping the new elements?

**Comment by mkver** [comment]
1. The [code](https://github.com/Matroska-Org/foundation-source/blob/2e5a1fa9910dc0c491a55257ea172b752152538f/mkclean/mkclean.c#L1501) does already allow to set the doctype to v4. In this mode v4 elements are no longer dropped. (But CueDuration and CueRelativePosition elements aren't written.)
2. But you shouldn't do it anyway: Most players (including ffmpeg-based players) reject (don't even try to play) v4 files. What would be good is support for writing v2 files with ReadDocType v4 that doesn't drop the extensions that v4 allows.

**Comment by dericed** [comment]
1. thanks, I see it's in the code now, but it's missing from the help doc
2. ffmpeg's matroska muxer writes docType=4 readDocType=2 by default.

**Comment by mkver** [comment]
2. You are right. I confused the two numbers. Actually `DocTypeVersion` must always be bigger than `DocTypeReadVersion` (that's the real name of the element; another thing I messed up earlier).

**Comment by robUx4** [comment]
This seems related to #34 in your case the v4 elements can be kept in mode 6.

There could be a mode that keeps the unknown elements. But then it would not be "cleaning" anymore...

Not closing as it's a legitimate feature request.

**Comment by Nottt** [comment]
Oh, so "skipping" here means dropping it from file?

**Comment by robUx4** [comment]
Yes, skipping, means dropping. For the SeekPreRoll it's not a big issue. The player may have to do more work on startup to find what it needs.

**Comment by robUx4** [comment]
> elements

The `readDocType` is always included in the `docType` (did we mention that in the EBML specs? Do we need to ? That seems obvious) and the skipping is always based on the `docType`.

**Comment by Nottt** [comment]
As of 2019, what is the recommend way to use mkclean with mkv files meant to be played back on web browsers, phones, smart tvs?

As of today, a file created with `mkvmerge` and cleaned with `mkclean` will drop the following:


```
The SeekPreRoll element at -1 is not part of profile 'matroska v2', skipping
The SeekPreRoll element at -1 is not part of profile 'matroska v2', skipping
The SeekPreRoll element at -1 is not part of profile 'matroska v2', skipping
The SeekPreRoll element at -1 is not part of profile 'matroska v2', skipping
The ChromaSitingHorz element at 459 is not part of profile 'matroska v2', skipping
The Colour element at 456 is not part of profile 'matroska v2', skipping
The FieldOrder element at -1 is not part of profile 'matroska v2', skipping
The SeekPreRoll element at -1 is not part of profile 'matroska v2', skipping
```

**Comment by Nottt** [comment]
It seems that using `--doctype 6` even VLC refuses to play the mkv :(

**Comment by dennyh** [comment]
Is it a bad idea to run this tool if my files have these elements?
```
The ChromaSitingHorz element at 412 is not part of profile 'matroska v2', skipping
The Colour element at 409 is not part of profile 'matroska v2', skipping
The FieldOrder element at -1 is not part of profile 'matroska v2', skipping
The SeekPreRoll element at -1 is not part of profile 'matroska v2', skipping
The SeekPreRoll element at -1 is not part of profile 'matroska v2', skipping
```

**Comment by robUx4** [comment]
There are many things are play here:
* if mkvmerge uses v4 elements it should mark the files as v4
* even if marked v4 it might be marked as readable by v2, this is an issue in mkclean as it considers the read version as the actual version, I need to fix this
* vlc should play files that v2 or v4 with no problem

**Comment by mbunkus** [comment]
> if mkvmerge uses v4 elements it should mark the files as v4

**Comment by robUx4** [comment]
I just double checked and v4 elements with a v4 targets are correctly allowed.
`TrackTimestampScale` is currently not allowed in v4 (only up to v3) that's why mkclean is not allowing it.
See Pull Request to allow it in newer files: https://github.com/ietf-wg-cellar/matroska-specification/pull/437

The `-1` position is the position where it was located in the source file. In this case `-1` means it was not in the original file (so mkvmerge is correct according to the current specs). It seems an internal bug of mkclean that automatically adds the (mandatory+default) element just to remove it later.
