### ISSUE TITLE
mkclean doesn't support the V_VP9 codec ID for the WebM profile

### ISSUE THREAD

**Issue by robUx4** [Matroska-Org/foundation-source#4]

**Comment by vhmth** [comment]
Is this as simple as just offering a way for people to link with the encoding lib or is there more magic here?

**Comment by robUx4** [comment]
I added them in the code. Although it's not clear if that's what consitutes WebM v2.

**Comment by vhmth** [comment]
Sweet thanks @robUx4! Doesn't seem like this updates the Homebrew formula though. Any way we could bump that?

**Comment by vhmth** [comment]
http://brewformulas.org/Mkclean

**Comment by robUx4** [comment]
Not sure how brew works. There is no new release of mkclean yet. There will be one as soon as I can turn the new Matroska EBML Schema into the semantic code used by libmatroska2.
