### ISSUE TITLE
specdata.xml: license and copyright

### ISSUE THREAD

**Issue by GreyCat** [Matroska-Org/foundation-source#43]
I want to clarify what is the license for [specdata.xml](https://github.com/Matroska-Org/foundation-source/blob/master/spectool/specdata.xml) and, subsequently, its rendition as [webpage](https://www.matroska.org/technical/specs/index.html)?

Official website [is also not clear about that](https://www.matroska.org/node/47), listing licenses for LibEBML, LibEBML2, LibMatroska and Core C, but not the specifications.

My aim is to create a specification for .mkv files using [Kaitai Struct](https://kaitai.io/) definition, so ideally I'd like to convert existing spec and reuse the comments / field names.

**Comment by robUx4** [comment]
The specdata.xml file is not used anymore and superseded by the [ebml_matroska.xml](https://github.com/cellar-wg/matroska-specification/blob/master/ebml_matroska.xml). This will be part of the [Matroska IETF RFC](https://datatracker.ietf.org/doc/draft-ietf-cellar-matroska/) is based on the format defined in [RFC 8794](https://www.rfc-editor.org/info/rfc8794).

The Copyright for the document is listed in the [temporary RFC](https://www.ietf.org/id/draft-ietf-cellar-matroska-05.html). As a code part, it's equivalent to the Simplified BSD license.
