### ISSUE TITLE
data2lib and data2lib2 segfault

### ISSUE THREAD

**Issue by mbunkus** [Matroska-Org/foundation-source#45]
Compiling a clean version at revision 15d0741c95849dadbe7b3c669ba427c1ba059fa4, then running `data2spec` in the `cellar-wg/matroska-specification` repo directory ends with a segfault:

```
[0 mosu@sweet-chili (master) ~/prog/video/matroska-specification] ../matroska-foundation/release/gcc_linux_x64/data2spec
unknown attribute length
unknown attribute recurring
unknown attribute length
unknown attribute length
unknown attribute length
unknown attribute length
unknown attribute recurring
unknown attribute length
unknown attribute length
unknown attribute length
unknown attribute recurring
unknown attribute length
did not parse element 'EBMLMaxIDLength' path \EBML\EBMLMaxIDLength
zsh: segmentation fault (core dumped)  ../matroska-foundation/release/gcc_linux_x64/data2spec
```

**Comment by mbunkus** [comment]
Same with `data2lib` and `data2lib2`.

**Comment by mbunkus** [comment]
Steve, please take a look at this. Thanks.

**Comment by robUx4** [comment]
You may try building the version from [this branch](https://github.com/Matroska-Org/foundation-source/tree/coremake-out/10).

I got rid of coremake and now builds everything with coremake. It's still a work in progress. But I did some fixes here and there in the code already building with newer compilers.

That being said, I don't plan to support the spectools based on core-c anymore. I will port everything to XSLT. I already started but it's still an ongoing effort.

**Comment by mbunkus** [comment]
Conversion to XSLT sounds good to me!

**Comment by mbunkus** [comment]
I've just given your branch `xslt/4` a try as there's a need to re-generate the semantics due to at least one element having wrong "mandatory" setting in the latest release. I noticed two problems:

1. The namespace of the `ebml_matroska.xml` document has changed. Therefore the `xmlns=…` and `xmlns:ebml=…` attributes in the stylesheets must be changed accordingly.
2. There are several elements that, in current `libmatroska`, aren't allowed to be written. That's handled by overwriting their `RenderData` functions. The stylesheets currently don't seem to support that, neither the one for the header nor the one for the `.cpp`. I'm therefore carefully hand-picking from the diffs which chunks to apply and which not to.

Additionally there are several empty lines removed from `KaxSemantic.h`, but I really don't care about this — meaning you don't have to spend time on getting those identical to how they were before.
