### ISSUE TITLE
mkvalidator 0.5.0 reports ERR201 for Matroska files created by mkvmerge with option --engage no_cue_duration

### ISSUE THREAD

**Issue by dvds** [Matroska-Org/foundation-source#5]
**Description**
What appear to be perfectly valid MKV files produced from mkvmerge with the hack --engage no_cue_duration makes mkvalidator return exit code 255 and report ERR201 to stderr.

examples:
ERR201: Invalid 'CueCodecState' for profile 'matroska v1' in CueTrackPositions at 3985449399
ERR201: Invalid 'CueCodecState' for profile 'matroska v1' in CueTrackPositions at 3985449495
ERR201: Invalid 'CueCodecState' for profile 'matroska v1' in CueTrackPositions at 3985449519

**tooling versions:**
mkvalidator v0.5.0, Copyright (c) 2010-2015 Matroska Foundation
mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 20:38:03

**Operating System:**
Ubuntu 14.04 (Linux N4030 3.13.0-51-generic #84-Ubuntu SMP Wed Apr 15 12:08:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux)

**Expected result:**
mkvalidator to return exit code 0 and not report ERR201 to stderr

**Actual result:**
mkvalidator returns exit code 255 and reports many ERR201 to stderr

**Comment by robUx4** [comment]
According to the specifications `CodecState` was added in Matroska v2. If your file says it's Matroska v1, it's wrong.

**Comment by mbunkus** [comment]
Should be fixed by https://github.com/mbunkus/mkvtoolnix/commit/5c853f1bcd76fe7a0d2b6ba259fa8921963983a7
