### ISSUE TITLE
Mkvalidator roadmap and 0.5.3 ETA ?

### ISSUE THREAD

**Issue by sviscapi** [Matroska-Org/foundation-source#65]
Dear @robUx4 ,

Happy New Year 🎉 

What's your roadmap for mkvalidator ? Would you have an ETA for the 0.5.3 release ?

On a side note, is the code on the master branch ready for production ?

Best regards,

Samuel, from CINES (Montpellier, France)
https://www.cines.fr/en/

**Comment by robUx4** [comment]
Hi,

I am reworking all the internals to be able to release libebml2 and libmatroska2 separately so each can evolve at their own speed, aside from mkvalidator and mkclean. I might also split the repositories.

There is no roadmap as I just work on it when I find the time. So there's no ETA either.

The current code is functional and easier to build now that it uses CMake (just open the repository in VS Code with the CMake extension and you're ready do build and debug).

As both mkvalidator and mkclean are very sensitive I have to make sure they don't introduce regressions, report incorrectly valid/invalid files or damage "cleaned" files. So release take longer than usual. I have a regression test suite for that but I didn't check it in a while.

Once all those pieces are ready I can make a release for each of them. And hopefully there will be some Linux maintainers that can make builds for their system.

In the meantime your best luck is to get the source and build it yourself.

**Comment by robUx4** [comment]
mkvalidator 0.6.0 has been released
https://github.com/Matroska-Org/foundation-source/releases/tag/mkvalidator-0.6.0
